### PR TITLE
fixed the styling on the trading page

### PR DESCRIPTION
**Pull request by kamara-moses**
changed the styling for the trading page.

### CODE REVIEW

**Comment by kamara-moses** [comment]
Screen Shot 2021-06-10 at 10 40 29 PM
Before

Screen Shot 2021-06-10 at 10 40 54 PM
After

**Comment by PremanandChowdhury** [comment]
Please add `assignee`-> your name, `labels` -> described in the issue if any & `add the issue` to the Linked Issue.
Also, Please add this PR  to the issue 👍🏼

**Review by PremanandChowdhury — APPROVED** [review]
Seems to be a small style change and the UI looks what is expected.
Approving from my side.
LGTM 🙂

**Review by swarajpure — CHANGES_REQUESTED** [review]
Why is package-lock changed? Please revert it
You could do `npm i` and trying pushing. It shouldn't show package-lock in changes on GitHub, it'll show in your recent commit though

**Comment by MehulKChaudhari** [comment]
@kamara-moses Would like to fix the conflicts so we can merge the PR?

**Comment by kamara-moses** [comment]
> @kamara-moses Would like to fix the conflicts so we can merge the PR?

@MehulKChaudhari Do I need to revert the changes made in the package-lock file?

**Comment by MehulKChaudhari** [comment]
> > @kamara-moses Would like to fix the conflicts so we can merge the PR?
> 
> @MehulKChaudhari Do I need to revert the changes made in the package-lock file?

No Pull the latest changes and do `npm install`. Do not forget to delete the node_modules and package-lock.json before doing it.

**Comment by kamara-moses** [comment]
Hey, can you take a look at this PR?
https://github.com/Real-Dev-Squad/website-crypto/pull/278

**Pull request closed without merging**
