### PR TITLE
refactor: make navbar component available to all routes from one place

### PR DESCRIPTION
**Pull request by Maianki**
## This PR closes issue#280

## Files changed/refactored:

- [x] pages/_app.js
- [x] pages/auction/index.js
- [x]  pages/auction/new.js
- [x] pages/cart.js
- [x] pages/currency-exchange/index.js
- [x] pages/index.js
- [x] pages/minting.js
- [x] pages/passbook.js
- [x] pages/shop/index.js
- [x] pages/trading/index.js
- [x] pages/trading/sell.js

## Demo after refactor

Untitled design(2)

### CODE REVIEW

**Comment by MehulKChaudhari** [comment]
LGTM. Exactly what was needed :fire:  

Just a question why is that white space above the Navbar? is it just in the video?

**Review by MehulKChaudhari — COMMENTED** [review]
Nicely done :fire:

**Review by MehulKChaudhari — APPROVED** [review]

**Comment by Maianki** [comment]
> LGTM. Exactly what was needed 🔥
> 
> Just a question why is that white space above the Navbar? is it just in the video?

Yeah that's a video thing I cropped it from top and bottom and that's why the whitespaces on top and bottom.

**Comment by MehulKChaudhari** [comment]
> > LGTM. Exactly what was needed fire
> > Just a question why is that white space above the Navbar? is it just in the video?
> 
> Yeah that's a video thing I cropped it from top and bottom and that's why the whitespaces are on top and bottom.
Ok, I checked it locally. Everything is a fine great job. Thank you :)

**Comment by MehulKChaudhari** [comment]
This PR closes #280

**Pull request merged**
